### ISSUE TITLE
Improve detect_plaintext method

### ISSUE THREAD

**Issue by stocyr** [nccgroup/featherduster#37]
Since the `detect_plaintext` function is used widely in cryptanalib, I suggest a few improvements that I encountered while prototyping my vigenere solver:
- the `pt_frequency_table_keys` list used for single letter analysis is built up at every call using `filter`, which causes a substantial performance decrease when using extensive brute-force attacks
- For the final score, the scores from word count and multigraph frequency deviation (two numbers with completely different scales and meanings) are added up in a mathematically ambiguous way. And also this "weighting" of the two scores is hard wired.
- The word count doesn't respect that longer words should contribute more to the score than smaller ones.
- Common english words with a length of two characters are already analyzed by the multigraph analysis and should therefore be ignored when both methods are in use.

**Comment by unicornsasfuel** [comment]
I definitely see the justification for adding frequency tables that don't include multigraphs to `cryptanalib.frequency` rather than using `filter` every single time. I was trying to optimize for the size of the code, but I think that's probably the wrong optimization.

I also agree regarding the problems with the word count vs multigraph frequency scores, and hard-coding their weights and such was only meant to be temporary (although it isn't marked that way, admittedly).

You also make a good point regarding the limitations of the current word count functionality, it was thrown in sort of slapdash.

I'd be happy to see these changes implemented in `detect_plaintext`, but as you say, it's widely used in cryptanalib and featherduster and as such any changes should be thought out carefully.

I like the idea of returning a tuple of different scores. I also like the idea of removing the `single_chars_only` option in favor of better frequency data in `cryptanalib.frequency`. Both of these things would break current usages of `detect_plaintext`, but I think that the code changes necessary to fix everything that would break would be worthwhile, especially since the codebase is still relatively young. Another thought occurred to me: Options to change the weighting of different methods, and an option to return individual scores instead of a single score.

Just tossing ideas around at this point, but you've definitely sold me on the need to improve the plaintext detection.

**Comment by unicornsasfuel** [comment]
Just pushed a few commits to improve performance of `detect_plaintext`, remove all uses of `single_chars_only`, fix a recently introduced bug in `analyze_ciphertext`, and pruned the common word list to remove two-character words.

Unfortunately, the plaintext detection has somehow suffered from these changes and I'll have to look into why, because this shouldn't have had any effect.

Still left:

* Allow for variable weighting

**Comment by unicornsasfuel** [comment]
Just pushed code to fix the issues with the plaintext detection as used by the multi-byte xor and many-time-pad solvers, they did not disable word detection in `detect_plaintext` as that was implied by `single_chars_only`, which was removed in favor of pre-filtered frequency tables.

I've also pushed commits to allow for multigraph frequency deviation and word count to be returned from `detect_plaintext` as a tuple with unweighted scores. I've also changed the word count score to be the total number of letters in all identified words (so a sample with 'the', 'when', and 'the' would have a word count score of 10).

I believe this addresses all the improvements you requested in this issue and as such, I'm closing it. If you feel that further improvements should be made or that my changes haven't properly addressed your requests, please leave a comment!

Thanks again for your contributions :)

**Comment by stocyr** [comment]
That's perfect :)

Am 11. September 2016 18:29:45 MESZ, schrieb unicornsasfuel <notifications@github.com>:
