### ISSUE TITLE
unit test failed : test_bleichenbacher.py

### ISSUE THREAD

**Issue by danielrocher** [nccgroup/featherduster#44]
```
$ python2.7 test_bleichenbacher.py 
Testing Bleichenbacher's oracle...
Original ciphertext is PKCS conforming, skipping blinding step and searching for s0...
Found s0! Starting to narrow search interval...
Found 2 possible r values, trying to narrow to one...
Current interval bit length: 0 | Iterations finished: 1003  Attack produced plaintext of '\x08\xf4\x03\x00\x00\x7f\x00\x00\x00\x02\x95V\x11]\x8f\x825[\xf5\xa3R\xd4J\x85q\x1be\xa6\xb2\x0c\x8d\xa3/\x02L58\x0eV\xccO\xe1\xfch\x16=\xf8\x8f\xb9\xe3\t\xc7\x18\xbfC\t\xea\xe3\xc9\xbdo\\N__\x8f\xcbV\xc7.\x15?u\x1c4\xe4\xe1\t\xe5\xe5\xe8\x16o\x1a\n\xca\xe8\n`\xa2\x19\xe0\x9a\n\xf9\x10\xcb%\x8d\tO\xd0\xb7\xed\xc8\xc7\x95\xee\x85\xde\x05\x95\x19\x1e\x96\xa2/\xa9\x82\xe4\xe9\x00test plaintexs'
Failed with 5184 queries
Traceback (most recent call last):
  File "test_bleichenbacher.py", line 24, in <module>
    raise BleichenbacherAttackFailedError

```

```
$ openssl version
OpenSSL 1.0.1f 6 Jan 2014

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```

**Comment by unicornsasfuel** [comment]
Looks like `test_bleichenbacher` wasn't placed in `__all__` in the tests module, so the bug in it wasn't being found. That's fixed!

Being completely honest, I coded this from the original paper and by looking at existing implementations, and I only understand this attack on a high level. I'm not sure why my implementation fails to produce the last bit correctly, but I do know that I can fix the bug, albeit in a very duct tape and twine sort of way, by brute forcing the last few bits of the message locally. Incidentally, this should also produce a minor performance increase in the bb98 function because we can do the calculations locally rather than querying what may be a very slow oracle, and it's a lot faster to `pow(candidate_message, e, N)` twice than it is to narrow down the interval bit length from 0 to 1 via bb98.

Once I produce this fix, I'll close this issue and open a new one to address the fact that this fix is going to be ugly.

**Comment by danielrocher** [comment]
Thank you for your prompt response :-)

**Comment by unicornsasfuel** [comment]
Okay, hacky fix is applied, bb98 test is improved, and bb98 test is added to test suite run by Travis-CI. Closing this issue.
