### ISSUE TITLE
Allow the results of a solver to be imported as new samples

### ISSUE THREAD

**Issue by gsingh93** [nccgroup/featherduster#47]
I ran into a problem recently where an alphanumeric shift was applied after a vigenere cipher. It'd be nice to directly import the new cipher and begin analysis on it as well as the original cipher.

**Comment by unicornsasfuel** [comment]
I've changed the title to what I assume you mean.

I'm not sure how this would work, especially with modules like the alpha shift solver which only have a statistical chance of success and rely on the user to identify the correct decryption. Additionally, since modules currently have no hard requirements to return data in any particular format, or even return data at all, it would be hard to have functionality in FeatherDuster to directly import the results instead of just copy/pasting using `import manualentry`.

Can you describe the workflow you're imagining for this? It seems like any way to do this would provide minimal benefit and would require imposing more restrictions on module writers, something I'm hesitant to do.

**Comment by gsingh93** [comment]
I wasn't too familiar with featherduster when I wrote this. All I really want now is to have an easier way to import the results of a previous analysis other than copy and paste. How about numbering the results of an analysis and allowing people to do `import <num>`?

**Comment by unicornsasfuel** [comment]
This is implemented! \o/

**Comment by gsingh93** [comment]
Well that was fast. Thanks!
