### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by bannsec** [nccgroup/featherduster#65]
Would love for this to be in python 3. I work with a lot of other crypto code and mostly it's in 3 now. Switching back and forth between environments can be a pain.

I did a 2-to-3 check on this, and it looks like your `ishell` reliance will make the transition difficult since they don't support 3 either.

**Comment by unicornsasfuel** [comment]
I'd like to move this to python3, but it's currently low priority for me.

I'd like to continue using `ishell` since the tab completion makes a huge usability difference, but I'm not sure how we can tailor it to our needs, and how much work that will take.

**Comment by italorossi** [comment]
https://github.com/italorossi/ishell/issues/19

**Comment by unicornsasfuel** [comment]
Quick update: `PyCryptodome` and `ishell` now both support Python3. It's just the CA/FD code that needs to be adapted to be compatible with Python3. I'd prefer to keep Python2 support as well, which makes things a bit more difficult, but not impossible.

**Comment by unicornsasfuel** [comment]
I finally got around to doing this, but there were too many structural changes needed with the whole `bytes`/`str` thing in Python3, so I forked Cryptanalib into its own project and, since Python2 is deprecated, I'll be maintaining [the fork](https://github.com/unicornsasfuel/cryptanalib3) instead. FeatherDuster3 soon to come.
