### ISSUE TITLE
Add featherduster to pypi

### ISSUE THREAD

**Issue by mlangbehn** [nccgroup/featherduster#67]
Currently, featherduster is findable via `pip search featherduster`, however it is not installable:

```shell
% pip install featherduster
Collecting featherduster
  Could not find a version that satisfies the requirement featherduster (from versions: )
No matching distribution found for featherduster
[1]    41436 exit 1     pip install featherduster
```

**Comment by unicornsasfuel** [comment]
This is known, albeit undocumented. Since anyone can register any name in PyPi, I wanted to register the name before someone else could throw a trojaned version of featherduster up on PyPi, but having never put anything up on PyPi, I figured I would do the least possible work to prevent such an attack and worry about it later.

**Comment by unicornsasfuel** [comment]
FeatherDuster is now on PyPI and can be installed via `pip`!
