### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by AlbertVeli** [nccgroup/featherduster#88]
I previously used featherduster (cryptanalib) with python2 and everything worked great. But now my linux-distribution is phasing out python2. Featherduster is in pip3 too, but it doesn't really work.
```
python test_vigenere.py 
Traceback (most recent call last):
  File "test_vigenere.py", line 1, in <module>
    import cryptanalib as ca
  File "/home/albert/.local/lib/python3.7/site-packages/cryptanalib/__init__.py", line 10, in <module>
    from helpers import *
  File "/home/albert/.local/lib/python3.7/site-packages/cryptanalib/helpers.py", line 117
    frequency_table = sorted(frequency_table.items(),key=lambda (k,v): (v,k), reverse=True)
                                                                ^
SyntaxError: invalid syntax
```
This looks like a python2/3 incompatibility to me.

Featherduster was installed with: pip install --user featherduster. No special options.

**Comment by unicornsasfuel** [comment]
FeatherDuster / Cryptanalib were Python2 only.

But good news! I've converted Cryptanalib over to Python3 and it's available here: https://github.com/unicornsasfuel/cryptanalib3. API is mostly compatible with the Python2 cryptanalib, but the functions all take `bytes` instead of `str` for any inputs, and the import statement is a little less painful to type: `import ca3`. I have a series of planned improvements and will be putting the Py3 fork up as `cryptanalib3` once I clean up the code a bit more. FeatherDuster will also be converted in time.

Rather than maintain both versions or attempt to maintain cross-compatibility, I'm abandoning work on this repo and will continue solely with the Python3 fork, which I'm calling `Cryptanalib3` to distinguish.

Thanks for using Cryptanalib!
